### PR TITLE
[WIP] Dogecoin 1.10.0

### PR DESCRIPTION
**Pull request by rockstardev**
Then Dogecoin docker image would be used like this:

https://github.com/rockstardev/btcpayserver/commit/06b5a5c5fbe4d00ab33558bf9d361d34954da428

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Can you use the same base image as Bitcoin Core and everything? It saves space.

**Comment by NicolasDorier** [comment]
Can you update the btcpay-docker instead of btcpayserver dev time docker-compose?

**Comment by rockstardev** [comment]
> 
> Can you use the same base image as Bitcoin Core and everything? It saves space.

Am I not using it already? `FROM debian:stretch-slim`?

**Comment by rockstardev** [comment]
> 
> 
> Can you update the btcpay-docker instead of btcpayserver dev time docker-compose?

https://github.com/btcpayserver/btcpayserver-docker/pull/64

I've left those references in `btcpayserver dev docker-compose` just to keep testing... will remove them when I do final PR in btcpayserver/btcpayserver repo

**Comment by NicolasDorier** [comment]
this is still `[WIP]` or ready to be merged? have you done `git update-index --chmod=+x entrypoint.sh` and commited it?

**Comment by NicolasDorier** [comment]
why is it closed?

**Pull request closed without merging**
