### PR TITLE
Refactor Groestlcoin Core and add 22.0

### PR DESCRIPTION
**Pull request by gruve-p**
Updated several docker entrypoints to match BTC
Added GROESTLCOIN_SHA256

### CODE REVIEW

**Comment by NicolasDorier** [comment]
No need to unify, problem with this type of PR is that it is hard to review and test while probably not useful to anyone.

That said, I can merge changes which only touch groestlcoin.

**Comment by gruve-p** [comment]
Sure thing.

Keep in mind that some places have the wrong Bitcoin versions:
https://github.com/NicolasDorier/docker-bitcoin/blob/master/core/0.16.3/Dockerfile#L10
https://github.com/NicolasDorier/docker-bitcoin/blob/master/core/0.17.1/Dockerfile#L10
https://github.com/NicolasDorier/docker-bitcoin/blob/master/core/0.21.1/Dockerfile#L10

**Comment by gruve-p** [comment]
This is now ready for review.

On another note would a PR to https://github.com/btcpayserver/dockerfile-deps be accepted for GRS?

**Comment by NicolasDorier** [comment]
sure

**Pull request merged**
